library(tidyverse)
library(readxl)
data <- read_excel("SARS-2_mortality_test_aula2.xlsx")
glimpse(data)
str(data)
class(data)
typeof(data)
save(data, file="SARS_data.rdata")
write_rds(data, "SARS_data.rds")
data2 <- read_rds("SARS_data.rds")
library(Hmisc)
janitor::clean_names(data2)
describe(data2$population_2019)

